### ISSUE TITLE
Implement "hide" button when editing dashboards

### ISSUE THREAD

**Issue by Rosiak** [librenms/librenmsv2#103]
Not super intuitive having to press the gear button to the left, to hide the menu, when having edited stuff on the right(Get's a little annoying on large monitors). There could be a simple arrow in place.

Or what do you think?

![screen shot 2016-04-25 at 22 08 55](https://cloud.githubusercontent.com/assets/6378934/14797320/70967428-0b32-11e6-9a8c-5eff4cd8ac36.png)

**Comment by murrant** [comment]
I think I would like a button in the upper right with a vertical ellipsis for page specific settings and tasks.

It would only be present on pages that have settings/tasks.

**Comment by murrant** [comment]
Also, I think Edit should be the default tab on this page.

**Comment by laf** [comment]
I'm not personally sure a button in the top navbar would be best, that area is expected to say fairly standard across each page and popping a new button in on random pages doesn't seem intuitive from a UX perspective.

I'd probably say a close button within the pop out would be best.

**Comment by murrant** [comment]
Android has this exact design as an "overflow" menu. If you are worried about things shifting around, you could reserve space for it.

But if the button for settings is always in the same place, people don't have to hunt around for it on each different page.  They will know that if a page has settings or actions, they will be under that button and they know where it will be.  If the button is missing, they can be assured there are no actions or settings on that page.

Also, this would mean we could reserve the center of the page for 100% content/functionality.

Just my thoughts.  Obviously, I'm a little biased from my Android experience.  But we do wish to target phones with our webui.
