### ISSUE TITLE
User management

### ISSUE THREAD

**Issue by Rosiak** [librenms/librenmsv2#104]
We need to simplify our menu system(Waaaay to many options as for now), heres a suggestion for the user management.

Change it a bit so menu wise it becomes:
Menu>
  Settings>
    Users>

Instead of:
 Menu>
   Settings>
     Add User>
     Remove User>
     Edit User>

http://www.jquery-bootgrid.com/Examples#basic-selection Should be used - Also edit/del icons should appear on each line(For each user) for quick changes.

Should also contain a dropdown for bulk actions.

What do you think?

**Comment by murrant** [comment]
I'm overall unhappy with the current menu layout, but waiting for more things to materialize so we can make a better decision.

If you look at issue #78 it is similar to this, so :+1: 

Also, we use [Datatables](https://www.datatables.net/) right now in v2
