### ISSUE TITLE
Missing rounded corners

### ISSUE THREAD

**Issue by murrant** [librenms/librenmsv2#127]
Any reason you took off the rounded corners? I kind of liked them.

https://github.com/librenms/librenmsv2/blob/develop/public/css/librenms.css#L29

I'm ok with the borders being removed I think.

**Comment by laf** [comment]
Was going for a cleaner condensed look, the rounded corners just make it appear like theres a bit more empty space.

**Comment by murrant** [comment]
Hmm, the rounding is slight, but I think it gives it a less mechanical look.

**Comment by laf** [comment]
V2's a playground so change things around and we'll come to agreements later :)

**Comment by murrant** [comment]
Sounds good.
