### ISSUE TITLE
root@librenms:/opt/librenms# ./validate.php

### ISSUE THREAD

**Issue by yandre-dle** [librenms/librenmsv2#147]
# root@librenms:/opt/librenms# ./validate.php 

Version info:
Commit SHA: 516e49b6d325c0278f7e5b645455b1921c83d3be
DB Schema: 126
PHP: 7.0.8-0ubuntu0.16.04.2
MySQL: 10.0.25-MariaDB-0ubuntu0.16.04.1
RRDTool: 1.5.5
SNMP: NET-SNMP version: 5.7.3
# 

[FAIL]    We have found some files that are owned by a different user than librenms, this will stop you updating automatically and / or rrd files being updated causing graphs to fail:
If you don't run a bespoke install then you can fix this by running `chown -R librenms:librenms /opt/librenms`
/opt/librenms/.git/ORIG_HEAD

[OK]      Database connection successful
root@librenms:/opt/librenms# 
root@librenms:/opt/librenms# 

how to fix [FAIL] ?

**Comment by killengage** [comment]
Its right there :)

Type this in your terminal session:

chown -R librenms:librenms /opt/librenms /opt/librenms/.git/ORIG_HEAD
