### ISSUE TITLE
White pages

### ISSUE THREAD

**Issue by kamils85** [librenms/librenmsv2#181]
Hello,

I followed the install guide and I managed to get v2 up and running but here is the problem I am experiencing. 

**The dashboard loads fine with no issues, the database connection seems to be working as I can see all devices I have added before.**
However every time I click on a device or port, it gives me a blank page with no error.

Most of the tabs don't work (they don't redirect anywhere).

Settings - Global Settings throws up this error:

> ErrorException in helpers.php line 519:
> htmlspecialchars() expects parameter 1 to be string, array given (View: /opt/librenmsv2/resources/views/components/form/ajax-dynamic-text.blade.php) (View: /opt/librenmsv2/resources/views/components/form/ajax-dynamic-text.blade.php) (View: /opt/librenmsv2/resources/views/components/form/ajax-dynamic-text.blade.php)

I have followed some suggestions from this topic #26 but this made no difference for me.

 `/opt/librenmsv2/storage/logs/laravel.log`

White page does not generate anything in laravel.log. 

When accessing Global settings I can see this:

> [2016-11-03 13:52:41] local.ERROR: ErrorException: htmlspecialchars() expects parameter 1 to be string, array given in /opt/librenmsv2/vendor/laravel/framework/src/Illuminate/Support/helpers.php:519
> Stack trace:
> #0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'htmlspecialchar...', '/opt/librenmsv2...', 519, Array)
> #1 /opt/librenmsv2/vendor/laravel/framework/src/Illuminate/Support/helpers.php(519): htmlspecialchars(Array, 3, 'UTF-8', false)
> #2 /opt/librenmsv2/vendor/laravelcollective/html/src/HtmlBuilder.php(452): e(Array)
> #3 /opt/librenmsv2/vendor/laravelcollective/html/src/HtmlBuilder.php(424): Collective\Html\HtmlBuilder->attributeElement('value', Array)
> #4 /opt/librenmsv2/vendor/laravelcollective/html/src/FormBuilder.php(276): Collective\Html\HtmlBuilder->attributes(Array)
> #5 /opt/librenmsv2/vendor/laravelcollective/html/src/FormBuilder.php(290): Collective\Html\FormBuilder->input('text', 'snmp.community', Array, Array)
> #6 /opt/librenmsv2/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(237): Collective\Html\FormBuilder->text('snmp.community', Array, Array)
> #7 /opt/librenmsv2/storage/framework/views/0e5e47a0fe2c16ef77dab67d515ff5099a5651e5.php(14): Illuminate\Support\Facades\Facade::__callStatic('text', Array)
> #8 /opt/librenmsv2/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(42): include('/opt/librenmsv2...')
> #9 /opt/librenmsv2/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('/opt/librenmsv2...', Array)
> #10 /opt/librenmsv2/vendor/laravel/framework/src/Illuminate/View/View.php(149): Illuminate\View\Engines\CompilerEngine->get('/opt/librenmsv2...', Array)

Nothing in the error.log.

Current permissions:

```
total 320
drwxr-xr-x 16 librenms librenms   4096 Nov  3 10:57 ./
drwxr-xr-x  4 root     root       4096 Oct 24 11:33 ../
drwxr-xr-x 14 librenms librenms   4096 Oct 24 11:33 app/
-rw-r--r--  1 librenms librenms   1739 Oct 24 11:33 artisan
drwxrwxr-x  3 librenms librenms   4096 Oct 24 11:33 bootstrap/
-rw-r--r--  1 librenms librenms   1707 Oct 24 11:33 composer.json
-rw-rw-r--  1 librenms librenms 174431 Nov  3 14:38 composer.lock
drwxr-xr-x  2 librenms librenms   4096 Oct 24 12:09 config/
drwxr-xr-x  5 librenms librenms   4096 Oct 24 11:33 database/
drwxr-xr-x  6 librenms librenms   4096 Oct 24 11:33 docs/
-rw-r--r--  1 librenms librenms    636 Nov  3 10:57 .env
-rw-r--r--  1 librenms librenms    589 Oct 24 11:33 .env.example
drwxr-xr-x  8 librenms librenms   4096 Nov  3 14:39 .git/
-rw-r--r--  1 librenms librenms     61 Oct 24 11:33 .gitattributes
drwxr-xr-x  2 librenms librenms   4096 Oct 24 11:33 .github/
-rw-r--r--  1 librenms librenms    223 Oct 24 11:33 .gitignore
-rw-r--r--  1 librenms librenms    553 Oct 24 11:33 gulpfile.js
-rw-r--r--  1 librenms librenms  35141 Oct 24 11:33 LICENSE
drwxrwxr-x  2 librenms librenms   4096 Oct 24 12:11 logs/
-rw-r--r--  1 librenms librenms    400 Oct 24 11:33 package.json
-rw-r--r--  1 librenms librenms    917 Oct 24 11:33 phpunit.xml
drwxr-xr-x  6 librenms librenms   4096 Oct 24 11:33 public/
-rw-r--r--  1 librenms librenms   2846 Oct 24 11:33 README.md
drwxrwxrwx  5 librenms librenms   4096 Oct 24 11:33 resources/
drwxr-xr-x  2 librenms librenms   4096 Oct 24 11:33 routes/
-rw-r--r--  1 librenms librenms    563 Oct 24 11:33 server.php
drwxrwxrwx  5 librenms librenms   4096 Oct 24 12:07 storage/
drwxr-xr-x  4 librenms librenms   4096 Oct 24 11:33 tests/
-rw-r--r--  1 librenms librenms    542 Oct 24 11:33 .travis.yml
drwxrwxrwx 44 librenms librenms   4096 Nov  3 14:39 vendor/
```

Any suggestions are welcome :)

Thanks,
Kamil

**Comment by murrant** [comment]
You get a blank page when you click on a device or a port because those pages haven't been written yet. :)

As for the htmlentities() error, no idea why you get that.  Possibly, you have an additional array wrapped around your community in your config.php file.
