### ISSUE TITLE
autodiscover does not search devices

### ISSUE THREAD

**Issue by tehseensagar** [librenms/librenmsv2#205]
This is an awesome NMS , but I'm facing little issue with auto discovery and MAP.

Ive added below config for 

################
# Discovery XDP
################

$config['autodiscovery']['xdp'] = true;
$config['autodiscovery']['ospf'] = true;
$config['autodiscovery']['bgp'] = true;
$config['discovery_modules']['discovery-arp'] = 1;

############
#  Network Allowed
#############
$config['nets'][] = "192.168.0.0/24";

#################
# Netork Map
##################

$config['network_map_items'] = array('mac','xdp');
$config['network_map_vis_options'] = '{
  "configure": { "enabled": true},
}';

$config['network_map_vis_options'] = '{
  "nodes": {
    "color": {
      "background": "rgba(20,252,18,1)"
    },
    "font": {
      "face": "tahoma"
    },
    "fixed": {
      "x": false,
      "y": false
    },
    "physics": false
  },
  "edges": {
    "smooth": {
      "forceDirection": "none"
    }
  },
  "interaction": {
    "hover": true,
    "multiselect": true,
    "navigationButtons": true
  },
  "manipulation": {
    "enabled": true
  },
  "physics": {
    "barnesHut": {
      "avoidOverlap": 0.11
    },

I've added discovery script in cron as per documentation and yet I'm unable to get my devices and I had to add manually its painful. In Map if I set fixed x , y it does not crate neat mapping all switched overlapped.

Regards

**Comment by laf** [comment]
Wrong repo, support is done at community.librenms.org
