### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by Stalker71** [librenms/librenmsv2#26]
Hi,

I followed the install guide but I'm stick on a blank login page.
I have doubt about the .env file and what wee need to change.

Any Idea?

**Comment by laf** [comment]
Thanks for testing :)

APP_KEY although that should have populated after running php artisan key:generate
DB_HOST=
DB_DATABASE=
DB_USERNAME=
DB_PASSWORD=

Check also you have:

API_STANDARDS_TREE=vnd
API_SUBTYPE=librenms
API_PREFIX=api
API_VERSION=v1
API_NAME=LibreNMS
API_STRICT=false
API_DEFAULT_FORMAT=json
API_DEBUG=true
API_THROTTLE=false

**Comment by Stalker71** [comment]
Thanks for you help. Here is my .env file:

APP_ENV=local
APP_DEBUG=true
APP_KEY=3q1GfVyVFeJiG7FdNpohb0wyvTKNX4lA

DB_HOST=127.0.0.1
DB_DATABASE=librenms
DB_USERNAME=librenms
DB_PASSWORD= PWD of Librenms

PHPUNIT_DB_HOST=127.0.0.1
PHPUNIT_DB_DATABASE=phpunit_librenms
PHPUNIT_DB_USERNAME=root
PHPUNIT_DB_PASSWORD=

CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

API_STANDARDS_TREE=vnd
API_SUBTYPE=librenms
API_PREFIX=api
API_VERSION=v1
API_NAME=LibreNMS
API_STRICT=false
API_DEFAULT_FORMAT=json
API_DEBUG=true
API_THROTTLE=false

**Comment by murrant** [comment]
You do have librenms installed on this host right?
Also, logs to check:

```
/opt/librenmsv2/logs/errro_log
/opt/librenmsv2/storage/logs/laravel.log
```

Check

```
php artisan route:list
php artisan api:routes
```

That should list all routes (pages) and api routes in the site.

If you figure it out, let us know so we can update the documentation ;)

**Comment by Stalker71** [comment]
Yes Librenms is already installed and working well

Did another try: I can see Permission denied in the logs/error_log files.
Owner of the directory is user librenms.

[Sat Feb 27 17:49:18.981751 2016] [:error] [pid 29924] [client 127.0.0.1:36648] PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/op
t/librenmsv2/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied' in /opt/librenmsv2/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php
:87\nStack trace:\n#0 /opt/librenmsv2/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\StreamHandler->write(Array)\n#1 /opt/librenmsv2
/vendor/monolog/monolog/src/Monolog/Logger.php(289): Monolog\Handler\AbstractProcessingHandler->handle(Array)\n#2 /opt/librenmsv2/vendor/monolog/monolog/src/Monolog/Logger.php(565
): Monolog\Logger->addRecord(400, Object(ErrorException), Array)\n#3 /opt/librenmsv2/vendor/laravel/framework/src/Illuminate/Log/Writer.php(202): Monolog\Logger->error(Object(Erro
rException), Array)\n#4 /opt/librenmsv2/vendor/laravel/framework/src/Illuminate/Log/Writer.php(113): Illuminate\Log\Writer->writeLog('error', Object(ErrorException), Array)\n#5 /o
pt/librenmsv2/vendor/laravel/framework/src/Illumina in /opt/librenmsv2/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 87

Apache configuration has been changed to the new directory librenmsv2.

**Comment by laf** [comment]
If you change the permissions for everything within storage/ and bootstrap/cache/ are writable by the web server that should fix that.

**Comment by laf** [comment]
p.s I hope you aren't expecting to use this as a replacement to the existing install as it's way off being production ready yet :)

**Comment by vitalisator** [comment]
had same problem with white page
Tested under debian (jessie 8.1)vith apache2

after installation apache still need write permissions to different /opt/librenmsv2 a 
directory /opt/librenmsv2/logs is absent after installation and should be included in git structure
`mkdir /opt/librenmsv2/logs` helps here too.

**Comment by laf** [comment]
I've edited your comment @vitalisator as those permissions aren't necessary for the entire install

**Comment by Stalker71** [comment]
Found the issue! :-)

in _/opt/librenmsv2_ : **php artisan cache:clear**

in _/opt/librenmsv2_ enter this command : 
**sudo chmod -R 777 storage**

in the file _.env_, instead of Travis part: 

DB_HOST=127.0.0.1
DB_DATABASE=librenms
DB_USERNAME= **librenms user**
DB_PASSWORD= **librenms Password**

And don't forget to mkdir logs directory in _/opt/librenmsv2_ and after do a **sudo chown -R librenms:librenms /opt/librenmsv2**
