### ISSUE TITLE
Database caching

### ISSUE THREAD

**Issue by murrant** [librenms/librenmsv2#30]
At some point implement Redis database caching.  Suggested library:
https://github.com/spiritix/lada-cache

**Comment by laf** [comment]
Laravel has Redis support: https://laravel.com/docs/5.2/redis using predis/predis. Better to stick with that?

**Comment by murrant** [comment]
Maybe what I was reading was out of date, but it sounded like the built in support didn't have automatic cache invalidation.  Lada cache is built on top of laravel cache.
