### ISSUE TITLE
Settings Design

### ISSUE THREAD

**Issue by murrant** [librenms/librenmsv2#56]
I have been working on a settings system for LibreNMS v2.  I need some input on a few points.
Primarily, it will be used like this:

```
Settings::put('snmp.version', 'v2c');
$snmpver = Settings::get('snmp.version');
```

Currently, it imports the data from defaults.inc.php and config.inc.php.  This data is available from `Config::get('config.key')`, which I include in Settings::get().
1. When returning data, should we return only values or nested arrays?  IE when a subtree is requested do we return null or an array of settings?
2. What about setting a value?
3. The plan is to have the DB override config.php.  To reset a value to the config.php value, `Settings::reset('key')`, to unset the value (set to null) `Settings::forget('key')`
4. The current config table contains display settings, should that be split out?  Why store this information in the database?
5. It also contains defaults.  Should this be in the database or in the code that requests the setting?
6. I would like to set config_name as the primary key of the config table.  I would also change this on the existing table, and maybe delete config_id, thoughts?
7. Any additional features?  Encryption? Contexts (user, device, etc)?

@librenms/core-team

**Comment by laf** [comment]
I'll preface this by saying the goal of v2 is to try and maintain backwards compatibility with v1. The main reason will be to allow people to transition from one to the other.
1. At present we return the nested array if one exists or a key / value if that's all there is. The reason it was done that way was to maintain support for config.php so we can more things over to the DB whilst anything people have already overwrote stays.
2. Same as above really.
3. The opposite is how it is done now, doing it the way suggested would mean that people will lose the settings they have unless they match our defaults (or we import from config.php - but what happens when someone next changes config.php?)
4. If we don't store this info in the DB where do you propose to store it?
5. It was done in the DB so that if people overwrite the value in the WebUI and want to go back to a default then they can. I have considered having all config option defaults as an array in a php file that loops through and gets imported as at present we do this by adding more inserts to the sql schema. Laravel migrations / seeding makes this a little easier as you can just reset the migration/seed for that config item and it will be re-imported.
6. That's fine, I do believe I've heard someone say they ended up with duplicate config_name entries so we need to clear those out first.
7. Encrypting the config? We could but we don't really store anything sensitive in there. We could start afresh with a settings table and have an import script to convert existing to new format and run that with daily.sh or discovery.php so it keeps things in synch (one way - old -> new).

**Comment by murrant** [comment]
@laf: Yes, this is the goal.  But I am prepared to make changes to both to move forward, obviously, I'd like to minimized changes.

1-2 v1 config is imported.  Items from config.php are translated to path by the built-in config system `Config::get('config.snmp.version')`.   Config::get returns nested arrays if you request a subtree. I wrap this in Settings.  The database is stored as strictly key->values.  So I have code that converts that to nested arrays and back.  It is complex.

3  If we want to move to a pimarily gui based config, don't we need this?  It could be complex and error prone to write changes into config.php.

4 Is it better to write custom gui for each item (contained in individual blade templates) or try to generate all of them in a generic way?

5  I can understand that.  One downside/upside of defining the default when requested is it allows for different defaults in different code.

6 Yeah, I looked into that and it takes a little tricky sql to do that.  I'll try to come up with something.

7 Currently, config.php is always imported.  So changes will be reflected in a live way, that will change a little when I enable caching.  I know we don't store anything sensitive now, but do we want to?

**Comment by laf** [comment]
1-2. Not sure if theirs a question in there but you know what we are trying to achieve so feel free to pave the way :)
1. Purely GUI based settings are fine as long as we can migrate people's config.php to the DB. If we can't then people would need to ensure they configure via the GUI everything they have changed. That might be a little tall order to ask.
2. Groups like we currently do maybe?
3. What are you thinking would need different defaults?
4. We don't store sensitive info at present (other than db creds) but we have got issues outstanding that would require us to store other credentials. We shy away from doing that at present but if we have a safe place to store them then we should use it I guess.

**Comment by adaniels21487** [comment]
Hi @murrant,
FYI: I am planning a re-work of the device configuration setup in: https://github.com/librenms/librenms/issues/3002.

It looks like we are crossing similar paths here. I have some code from another project where I have dome something similar, but apart from that I havent really started yet. anything I can do to help?

Aaron

**Comment by murrant** [comment]
@adaniels21487 Even just input would be great.  Code would be great too.  You can see the current state in the PR.  Thanks.

**Comment by murrant** [comment]
@laf I'm still debating whether we should have config.php overrride the db or not.  If we do have config.php override, I think we would need some sort of indication in the gui to tell users when settings need to be removed from config.php before they can set them in the gui.  Thoughts?

**Comment by laf** [comment]
I think we should still maintain config.php overrides anything else.

Doing the indication within the webui is ok to do, ajax call for the config item, backend then loads config.php and sees if the config item is set. Sounds easier than it might be but possible.

**Comment by murrant** [comment]
Hmm, we could add a variable per config item to set if it overrides config.php.  That would allow us to override without touching config.php, but allow config.php to override by default.

**Comment by laf** [comment]
You mean so if someone adds / changes something in config.php, we detect this and import that into the DB?

**Comment by murrant** [comment]
No I mean this:
Say we have `$config['snmp.version'] = 'v2';` set in config.php.
In the gui, the user sees the value is set to v2, they change it to v3 in the gui.

If the DB takes precedence over config.php, we are done.

If config.php takes precedence over the DB config, we have two options:
1. Tell the user to go delete the variable from config.php
2. Set an override variable to specify that the DB overrides config.php for this one setting.

**Comment by laf** [comment]
Makes sense :)

**Comment by mrunkel** [comment]
Hey, sorry to barge in here, but I gotta say this doesn't sound optimal to me.   It sounds like you guys are trying to overload the config.php file.  It's both "the old way to configure the box" and "the way to override the database."

I think if the goal is to maintain backwards compatibility then you'd want to read config.php _once_ and then migrate the settings into the database.  Once that is done, I'd never read config.php again.

If you want the capability to override database settings, make a new file called overrides.php or something like that and use that going forward.   To try to use the existing config.php will just make documenting this very confusing and will have unintended consequences.  

For example, as you've described it, all my existing config.php settings will become overrides upon upgrade, when that's probably not what I intended.

Totally new to the project, so forgive me for barging in, but sometimes "new eyes" can be valuable. :)

**Comment by murrant** [comment]
@mrunkel You have a point, but the problem is **polling and discovery still will use config.php for now**.  I'm not sure we want to take away the option to use only config.php.

This is sort of step one: prototyping database based config for v2.  We still need to make v1 use the database settings.

I the main question I have been pondering on this is whether the database should override config.php or the opposite?  I am leaning towards the latter for consistency with v1.  I think it would be viable to lock settings that are set in config.php and give an indication that they can set it in the gui if they delete it from config.php.
