### ISSUE TITLE
Additional command line user management

### ISSUE THREAD

**Issue by murrant** [librenms/librenmsv2#63]
Currently, you can add users from the command line with `php artisan user:add`

Make this also support `php artisan user:delete`.

Most importantly, create some tests and documentation for these commands.

**Comment by pheinrichs** [comment]
@murrant I don't see why it would be an issue having this. I started it this afternoon and is working correctly for me. Do you see anything you would like changed?

```

$headers = ['ID','username','realname','email'];
$user = $this->argument('user');
$user_list = User::select('user_id','username','realname','email')->where('username', 'like', '%'.$user.'%')->orWhere('realname','like', '%'.$user.'%')->get()->toArray();
        $this->table($headers,$user_list);
        $userid = $this->ask('Enter the ID you wish to remove');
        $remove_user = User::find($userid);
        if ($this->confirm('Do you wish to remove '.$remove_user->realname.'? [y|N]')) {
            $remove_user->delete();
        }
```

**Comment by murrant** [comment]
This is a todo item for adding additional features, documentation and tests for the `php artisan user` command.
I wrote what is there already, just suggesting as this as an opportunity for someone else to get their feet wet.
I don't recognize the code you pasted, is it something you wrote?

**Comment by murrant** [comment]
Sorry, misread your comment.
Please send a pull request, it makes it easier to review.
Looks good, but you should skip the table if there is only one result.

**Comment by murrant** [comment]
Oh and don't allow the user to type the actual user ID to avoid typos, use choice instead of table.

**Comment by murrant** [comment]
Needs documentation still.

**Comment by pheinrichs** [comment]
@murrant I'll write something up under docs/General/ for commands.
