### ISSUE TITLE
Installation on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by jg75996** [librenms/librenmsv2#65]
Attempted installation of librenmsv2 via the documentation.  Got as far as downloading a copy and configuring the .env file settings.

Went to install using the command 'composer install' and encountered a warning and an error.
Cannot create cache directory /home/user/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /home/user/.composer/cache/files/, or directory is not writable. Proceeding without cache

> php artisan clear-compiled
> PHP Warning:  require(/opt/librenmsv2/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /opt/librenmsv2/bootstrap/autoload.php on line 17
> PHP Fatal error:  require(): Failed opening required '/opt/librenmsv2/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /opt/librenmsv2/bootstrap/autoload.php on line 17
> Script php artisan clear-compiled handling the pre-update-cmd event returned with an error

  [RuntimeException]
  Error Output: PHP Warning:  require(/opt/librenmsv2/bootstrap/../vendor/aut
  oload.php): failed to open stream: No such file or directory in /opt/libren
  msv2/bootstrap/autoload.php on line 17
  PHP Fatal error:  require(): Failed opening required '/opt/librenmsv2/boots
  trap/../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pea
  r') in /opt/librenmsv2/bootstrap/autoload.php on line 17

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...

When the command is executed using sudo, 'sudo composer install', the follow warning and error is recevied:
Running composer as root is highly discouraged as packages, plugins and scripts cannot always be trusted

> php artisan clear-compiled
> PHP Warning:  require(/opt/librenmsv2/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /opt/librenmsv2/bootstrap/autoload.php on line 17
> PHP Fatal error:  require(): Failed opening required '/opt/librenmsv2/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /opt/librenmsv2/bootstrap/autoload.php on line 17
> Script php artisan clear-compiled handling the pre-update-cmd event returned with an error

  [RuntimeException]
  Error Output: PHP Warning:  require(/opt/librenmsv2/bootstrap/../vendor/aut
  oload.php): failed to open stream: No such file or directory in /opt/libren
  msv2/bootstrap/autoload.php on line 17
  PHP Fatal error:  require(): Failed opening required '/opt/librenmsv2/boots
  trap/../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pea
  r') in /opt/librenmsv2/bootstrap/autoload.php on line 17

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...

This was done on a system where librenms and librenmsv2 would be running together.
From the librenms About screen:
Version d8e4187
DB Schema   #102
Apache  2.4.7 (Ubuntu)
PHP 5.5.9-1ubuntu4.14
MySQL   5.5.47-MariaDB-1ubuntu0.14.04.1
RRDtool 1.4.7

**Comment by murrant** [comment]
First try:
`chmod -R g+w boostrap/cache`

If that doesn't work, run:
`chmod -R g+w boostrap`

I added the first to the documentation just now, but it looks like you might need the second one in your case.  Let me know which one works so I can update the docs (or send a Pull Request).

**Comment by jg75996** [comment]
Hello Mr. Murray,

I tried both methods as suggested and tried re-installing, without using sudo first and then with sudo, but I received the same results.

Thanks for your quick reply!

**Comment by murrant** [comment]
What permissions do you have for /opt/librenmsv2/bootstrap and the cache folder inside that?

**Comment by jg75996** [comment]
Permissions are as follows:
drwxrwxr-x  3 librenms librenms  4096 Apr  1 14:44 bootstrap/

and for the cache folder:
drwxrwxr-x  2 librenms librenms 4096 Apr  1 14:44 cache/

**Comment by murrant** [comment]
I re-read your error.  I think the issue is with your .composer directory.  The location reported looks odd,  what is the home directory for the user you are running composer as?

**Comment by jg75996** [comment]
The full path for the home directory of the user that I am logged in as, is:
/home/user.

The contents of the .composer directory is:
user@phs-librenms:/opt/librenmsv2$ ls ~/.composer
cache  keys.dev.pub  keys.tags.pub

Permissions are:
drwxr-xr-x 3 root root 4096 Apr  1 14:47 .
drwxr-xr-x 5 user user 4096 Apr  1 14:44 ..
drwxr-xr-x 4 root root 4096 Apr  1 14:47 cache
-rw-r--r-- 1 root root   13 Apr  1 14:47 .htaccess
-rw-r--r-- 1 root root  799 Apr  1 14:44 keys.dev.pub
-rw-r--r-- 1 root root  799 Apr  1 14:44 keys.tags.pub

**Comment by murrant** [comment]
There is your problem.  Just nuke that directory and run composer install again.

Or, run composer install as the librenms user.

**Comment by jg75996** [comment]
Okay.  Nuked the directory, logged off and then back on using the librenms user.  Attempted another install of composer:
$curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/bin --filename=composer
[sudo] password for librenms:
All settings correct for using Composer
Downloading 1.0.0-beta2...

Composer successfully installed to: /usr/bin/composer
Use it: php /usr/bin/composer
$ composer install
Composer could not find a composer.json file in /opt/librenms
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section

Changed to the librenmsv2 directory and attempted another install.
$ cd librnmsv2
$ composer install

> php artisan clear-compiled
> PHP Warning:  require(/opt/librenmsv2/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /opt/librenmsv2/bootstrap/autoload.php on line 17
> PHP Fatal error:  require(): Failed opening required '/opt/librenmsv2/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /opt/librenmsv2/bootstrap/autoload.php on line 17
> Script php artisan clear-compiled handling the pre-update-cmd event returned with an error

  [RuntimeException]
  Error Output: PHP Warning:  require(/opt/librenmsv2/bootstrap/../vendor/aut
  oload.php): failed to open stream: No such file or directory in /opt/libren
  msv2/bootstrap/autoload.php on line 17
  PHP Fatal error:  require(): Failed opening required '/opt/librenmsv2/boots
  trap/../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pea
  r') in /opt/librenmsv2/bootstrap/autoload.php on line 17

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...

Thank you!

**Comment by murrant** [comment]
Ok, this looks better. It looks like you don't have a vendor directory yet.
Try this:
`composer install --no-scripts`

Then if that works run `composer update` for good measure.

**Comment by jg75996** [comment]
I was able to complete the 'composer install --no-scripts' command.
Also ran 'composer update'.
Was then able to continue and did 'sudo php artisan key:generate'
Then 'sudo usermod -a -G librenms www-data'
and 'sudo chmod -R g+w storage bootstrap/cache logs'

On to modifying the web server piece...
Ubuntu has apache2 as the default web server.
There is an existing config for librenms at /etc/apache2/sites-enabled/librenms.conf

Would this be the correct file to modify?

**Comment by murrant** [comment]
Leave that and create a new file for v2.  That way you can access both.  Either use different virtual host names or different ports.

**Comment by jg75996** [comment]
I have created a new config file (named librenmsv2.conf) using the contents of the librenms.conf and changed it accordingly:

```
 <VirtualHost *:81>
   DocumentRoot /opt/librenmsv2/html/
   CustomLog /opt/librenmsv2/logs/access_log combined
   ErrorLog /opt/librenmsv2/logs/error_log
   AllowEncodedSlashes NoDecode
   <Directory "/opt/librenmsv2/html/">
     Require all granted
     AllowOverride All
     Options FollowSymLinks MultiViews
   </Directory>
 </VirtualHost>
```

Restarted the apache2 service and got a warning:
- Restarting web server apache2  
  AH00112: Warning: DocumentRoot [/opt/librenmsv2/html/] does not exist                                    [ OK]

**Comment by murrant** [comment]
it should be /opt/librenmsv2/public not /opt/librenmsv2/html.

You must have pulled that config awhile ago, the current docs reflect that change.

**Comment by jg75996** [comment]
I was following the Install document on GitHub that has stated:

```
Web Server

Now you will need to create your web server config and modify as needed.

Distro  Web Server  Config
CentOS / RHEL, Ubuntu / Debian  Apache 2.2.17 or lower  Config
CentOS / RHEL, Ubuntu / Debian  Apache 2.2.18 or later  Config
CentOS / RHEL, Ubuntu / Debian  Nginx   Config
If you want to run this on the same server as your current LibreNMS install on another port then just modify the beginning of your webserver config:

Apache:

Listen 81
<VirtualHost *:81>
```

**Comment by murrant** [comment]
Change any reference of /opt/librenmsv2/html to /opt/librenmsv2/public.

**Comment by jg75996** [comment]
Thank you.  I have successfully been able to install the new interface.

**Comment by murrant** [comment]
Good to hear.

Keep in mind that this is basically a preview and under heavy development, we might break stuff as we go.

We do appreciate contributions to help get things going :)

**Comment by murrant** [comment]
Good to hear.

Keep in mind that this is basically a preview and under heavy development, we might break stuff as we go.

We do appreciate contributions to help get things going :)
