### ISSUE TITLE
folderstructure divergence from 'ordinary' laravel installs

### ISSUE THREAD

**Issue by f0o** [librenms/librenmsv2#9]
Hi,

Just reading through the code a bit and I wonder why we moved away from the MVC folder structure of laravel.

For instance I'm missing the views and models folders.

**Comment by laf** [comment]
The folder structure hasn't changed:

https://github.com/librenms/librenmsv2/tree/develop/resources/views

**Comment by f0o** [comment]
Ahh i was expecting it under app :D

**Comment by laf** [comment]
Where it is is the default location as far as I know.

**Comment by f0o** [comment]
No clue really, all the laravel installs I've touched so far had everything in app/ and the html-folder was also 'public/' ... But well doesnt matter, was just confused at first haha

**Comment by laf** [comment]
Changed the public folder to html inline with the current webui but it can be changed to public if people think it needs to be that. Rest of it has stayed the same.

Even laravel's main branch shows the views in resources: https://github.com/laravel/laravel/tree/master/resources/views
